//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFFDR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FM-MMERCADO-L;Initial Catalog=hr_database_1;Integrated Security=SSPI;" +
            "")]
        public string hr_database_1ConnectionString1 {
            get {
                return ((string)(this["hr_database_1ConnectionString1"]));
            }
            set {
                this["hr_database_1ConnectionString1"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FM-MMERCADO-L;Initial Catalog=hr_dbase;Integrated Security=SSPI;")]
        public string hr_dbaseConnectionString {
            get {
                return ((string)(this["hr_dbaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FM-MMERCADO-L;Initial Catalog=hr_database_1;Integrated Security=SSPI;" +
            "")]
        public string hr_database_1ConnectionString {
            get {
                return ((string)(this["hr_database_1ConnectionString"]));
            }
            set {
                this["hr_database_1ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Reports")]
        public string rpt_path {
            get {
                return ((string)(this["rpt_path"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Reports")]
        public string fdg {
            get {
                return ((string)(this["fdg"]));
            }
            set {
                this["fdg"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.2.16,1433\\SQLEXPRESS;Initial Catalog=Fedoramain;User ID=sa;Pass" +
            "word=FMf3dor@2o20;MultipleActiveResultSets=true;")]
        public string hr_bakConnectionString {
            get {
                return ((string)(this["hr_bakConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.2.16,1433\\SQLEXPRESS;Initial Catalog=Fedoramain;User ID=sa;Pass" +
            "word=FMf3dor@2o20;MultipleActiveResultSets=true;")]
        public string hr_application_conn2 {
            get {
                return ((string)(this["hr_application_conn2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.2.16,1433\\SQLEXPRESS;Initial Catalog=Fedoramain;User ID=sa;Pass" +
            "word=FMf3dor@2o20;MultipleActiveResultSets=true;")]
        public string hr_application_conn {
            get {
                return ((string)(this["hr_application_conn"]));
            }
        }
    }
}
